# Generated by Otto, do not edit manually.
#
# Otto uses outputs as the method for transferring data from Terraform
# back into Otto that will be used for deploys, future infrastructure
# change, etc.
#
# Because of the importance of these values for Otto to function, care
# should be taken if these are modified.

output "region" {
    value = "${var.aws_region}"
}

output "vpc_id" {
    value = "${module.vpc.vpc_id}"
}

output "vpc_cidr" {
    value = "${module.vpc.vpc_cidr}"
}

output "subnet_public" {
    value = "${module.vpc.public_subnet_ids}"
}

output "key_name" {
    value = "${module.vpc.key_name}"
}

output "infra_id" {
    value = "${module.vpc.infra_id}"
}

output "bastion_host" {
    value = "${element(split(",",module.consul.server_public_addresses),0)}"
}

output "nomad_host" {
    value = "${element(split(",",module.consul.server_addresses),0)}"
}
